### ISSUE TITLE
Drop out peerDependencies

### ISSUE THREAD

**Issue by TrySound** [sairion/buble-loader#21]
PeerDependencies can't be resolved well automatically. And your last update broke our build.
1. Move buble to dependencies to not break builds when upgrade
2. Remove webpack because this package is not dependent to webpack at all. Users can decide how to use it.

**Comment by sairion** [comment]
Yeah, your points seems pretty fair! Shame, I wasn't even aware Webpack is not dependent. (We could make use of it for future release though, but I'm not actively developing this now)

**Comment by sairion** [comment]
I considered again. I think this lib is still dependent to Webpack API (although it does not directly require webpack) and I can't think use case other than using this lib as Webpack loader. I think Webpack should remain as deps. I will add Buble as dependency though.

**Comment by TrySound** [comment]
Today webpack rc was released. And I again can't use it because of shity peerDependencies. And again I don't think it's necessary. Without installed webpack you won't do anything so you don't need to force people about it, they will be forced by default.

**Comment by TrySound** [comment]
Btw there's already buble0.15

**Comment by sairion** [comment]
I don't agree about moving out Webpack as any deps but I will move out `peerDependencies` to `dependencies`, since I don't need it and seems to be causing problems...

p.s. Please consider your tone of speech, as far as I'm not like any regular OSS maintainers, or 'OSS activist' whom listen to any kind of voice on issues. I just upload what I make and that is pretty much it. I don't make living with OSS or anything like that. This is the last one.

**Comment by sairion** [comment]
https://github.com/sairion/buble-loader/commit/c41063e0d3c7fbf337f94d2f24fad921db98bed1

**Comment by TrySound** [comment]
Thanks
